FROM alpine

RUN apk add --no-cache gcc cmake make pkgconf musl-dev linux-headers bsd-compat-headers curl-dev openssl-dev libarchive-dev

COPY . /libacquire

WORKDIR /libacquire/build

RUN cmake -DCMAKE_BUILD_TYPE="Debug" .. && \
    cmake --build .

CMD ctest .

ENTRYPOINT ["/libacquire/build/acquire", "--version"]
