FROM debian

COPY . /libacquire

WORKDIR /libacquire/build

RUN apt-get update -qq && \
    apt-get install -y gcc make cmake libc-dev libssl-dev && \
    cmake -DCMAKE_BUILD_TYPE="Debug" .. && \
    cmake --build .

CMD ctest .

ENTRYPOINT ["/libacquire/build/acquire", "--help"]
