function(set_extract_lib)
    if (CMAKE_SYSTEM_NAME STREQUAL "Windows"
            AND NOT DEFINED LIBACQUIRE_USE_ZLIB
            AND NOT DEFINED LIBACQUIRE_USE_LIBARCHIVE
            AND NOT DEFINED LIBACQUIRE_USE_MINIZ)
        set(LIBACQUIRE_USE_WINCOMPRESSAPI 1 PARENT_SCOPE)
        set(EXTRACT_LIB "WINCOMPRESSAPI" PARENT_SCOPE)
        list(APPEND _Header_Files "acquire_wincompressapi.h")
    elseif (DEFINED LIBACQUIRE_USE_LIBARCHIVE)
        set(EXTRACT_LIB "LIBARCHIVE" PARENT_SCOPE)
        list(APPEND _Header_Files "acquire_libarchive.h")
        include("${CMAKE_SOURCE_DIR}/cmake/FindLibArchiveCustom.cmake")
        set(EXTRACT_INCLUDE_DIRECTORIES "${LibArchive_INCLUDE_DIRS}" PARENT_SCOPE)
        list(APPEND LIBACQUIRE_LIBRARIES "${LibArchive_LIBRARIES}")
    elseif (DEFINED LIBACQUIRE_USE_ZLIB)
        set(LIBACQUIRE_USE_ZLIB 1 PARENT_SCOPE)
        set(EXTRACT_LIB "ZLIB" PARENT_SCOPE)
        list(APPEND _Header_Files "acquire_zlib.h")
    else ()
        set(LIBACQUIRE_USE_MINIZ 1 PARENT_SCOPE)
        set(EXTRACT_LIB "kubazip::kubazip" PARENT_SCOPE)
        list(APPEND _Header_Files "acquire_miniz.h")
    endif ()
endfunction(set_extract_lib)
