function(target_link_libraries_once library visibility library_to_link)
    get_target_property(linked_libs "${library}" LINK_LIBRARIES)
    list(FIND linked_libs "${library}" lib_index)
    if (lib_index EQUAL -1)
        target_link_libraries("${library}" "${visibility}" "${library_to_link}")
    else ()
        message(STATUS "${library} already linked with '${library_to_link}'")
    endif (lib_index EQUAL -1)
endfunction(target_link_libraries_once library visibility library_to_link)
