name: CI for Linux, Windows, macOS

on: [push]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev
          mkdir cmake-build-"$GITHUB_ACTION"-debug && cd "$_"
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          brew install pkg-config  # openssl
          mkdir cmake-build-"$GITHUB_ACTION"-debug && cd "$_"
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          md cmake-build-debug
          cd cmake-build-debug
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
