name: CI for Linux, Windows, macOS

on:
  push:
    branches:
      - master

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev
      - name: build
        run: |
          mkdir cmake-build-"$RUNNER_OS"-debug && pushd "$_"
          cmake -DCMAKE_BUILD_TYPE="Debug" ..
          cmake --build .
      - name: test
        run: ctest .
      - name: release
        run: |
          cd "$GITHUB_WORKSPACE"
          echo "${{ secrets.GITHUB_TOKEN }}" > .token
          gh auth login --with-token < .token
          rm .token
          gh release delete -y amalgamation
          gh release create amalgamation --target master cmake-build-"$RUNNER_OS"-debug/src/acquire.h
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: brew install pkg-config  # openssl
      - name: build
        run: |
          mkdir cmake-build-"$RUNNER_OS"-debug && cd "$_"
          cmake -DCMAKE_BUILD_TYPE="Debug" ..
          cmake --build .
      - name: test
        run: ctest .
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          md cmake-build-debug
          cd cmake-build-debug
          cmake ..
          cmake --build .
      - name: test
        run: ctest .
