name: CI for Linux, Windows, macOS

on: [push]

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev
      - name: build
        run: |
          mkdir cmake-build-"$GITHUB_ACTION"-debug && pushd "$_"
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
          popd
      - name: test
        run: ctest .
      - name: release
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > .token
          gh auth login --with-token < .token
          rm .token
          find cmake-build-"$GITHUB_ACTION"-debug -type f -name '*.h'
          gh release create amalgamation --target master -d cmake-build-"$GITHUB_ACTION"-debug/src/acquire_amalgamation.h
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: brew install pkg-config  # openssl
      - name: build
        run: |
          mkdir cmake-build-"$GITHUB_ACTION"-debug && cd "$_"
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
      - name: test
        run: ctest .
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          md cmake-build-debug
          cd cmake-build-debug
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
      - name: test
        run: ctest .
